"""
Satisfactory 1.0 recipes - complete list from MAZ01001/SatisfactoryFlowchart data.json
Format: (name, [(input_item, qty_per_cycle), ...], [(output_item, qty), ...], [machines], duration_sec)
"""

RECIPES = [
    # Format: name, inputs, outputs, machines, duration
    ("Adaptive Control Unit", [("Circuit Board",5),("Computer",2),("Heavy Modular Frame",1),("Automated Wiring",5)], [("Adaptive Control Unit",1)], ["Manufacturer"], 60),
    ("AI Expansion Server", [("Excited Photonic Matter",25),("Superposition Oscillator",1),("Magnetic Field Generator",1),("Neural-Quantum Processor",1)], [("Dark Matter Residue",25),("AI Expansion Server",1)], ["Quantum Encoder"], 15),
    ("AI Limiter", [("Copper Sheet",5),("Quickwire",20)], [("AI Limiter",1)], ["Assembler"], 12),
    ("Alclad Aluminum Sheet", [("Aluminum Ingot",3),("Copper Ingot",1)], [("Alclad Aluminum Sheet",3)], ["Assembler"], 6),
    ("Alien DNA Capsule", [("Alien Protein",1)], [("Alien DNA Capsule",1)], ["Constructor"], 6),
    ("Alien Power Matrix", [("Power Shard",3),("Excited Photonic Matter",24),("Superposition Oscillator",3),("SAM Fluctuator",5)], [("Alien Power Matrix",1),("Dark Matter Residue",24)], ["Quantum Encoder"], 24),
    ("Alternate: Adhered Iron Plate", [("Iron Plate",3),("Rubber",1)], [("Reinforced Iron Plate",1)], ["Assembler"], 16),
    ("Alternate: Alclad Casing", [("Aluminum Ingot",20),("Copper Ingot",10)], [("Aluminum Casing",15)], ["Assembler"], 8),
    ("Alternate: Aluminum Beam", [("Aluminum Ingot",3)], [("Steel Beam",3)], ["Constructor"], 8),
    ("Alternate: Aluminum Rod", [("Aluminum Ingot",1)], [("Iron Rod",7)], ["Constructor"], 8),
    ("Alternate: Automated Miner", [("Iron Plate",4),("Steel Pipe",4)], [("Portable Miner",1)], ["Assembler"], 60),
    ("Alternate: Automated Speed Wiring", [("High-Speed Connector",1),("Stator",2),("Wire",40)], [("Automated Wiring",4)], ["Manufacturer"], 32),
    ("Alternate: Basic Iron Ingot", [("Iron Ore",5),("Limestone",8)], [("Iron Ingot",10)], ["Foundry"], 12),
    ("Alternate: Biocoal", [("Biomass",5)], [("Coal",6)], ["Constructor"], 8),
    ("Alternate: Bolted Frame", [("Reinforced Iron Plate",3),("Screw",56)], [("Modular Frame",2)], ["Assembler"], 24),
    ("Alternate: Bolted Iron Plate", [("Iron Plate",18),("Screw",50)], [("Reinforced Iron Plate",3)], ["Assembler"], 12),
    ("Alternate: Cast Screw", [("Iron Ingot",5)], [("Screw",20)], ["Constructor"], 24),
    ("Alternate: Caterium Circuit Board", [("Quickwire",30),("Plastic",10)], [("Circuit Board",7)], ["Assembler"], 48),
    ("Alternate: Caterium Computer", [("Circuit Board",4),("Quickwire",14),("Rubber",6)], [("Computer",1)], ["Manufacturer"], 16),
    ("Alternate: Caterium Wire", [("Caterium Ingot",1)], [("Wire",8)], ["Constructor"], 4),
    ("Alternate: Charcoal", [("Wood",1)], [("Coal",10)], ["Constructor"], 4),
    ("Alternate: Cheap Silica", [("Raw Quartz",3),("Limestone",5)], [("Silica",7)], ["Assembler"], 8),
    ("Alternate: Classic Battery", [("Alclad Aluminum Sheet",7),("Plastic",8),("Sulfur",6),("Wire",12)], [("Battery",4)], ["Manufacturer"], 8),
    ("Alternate: Cloudy Diamonds", [("Coal",12),("Limestone",24)], [("Diamonds",1)], ["Particle Accelerator"], 3),
    ("Alternate: Coated Cable", [("Heavy Oil Residue",2),("Wire",5)], [("Cable",9)], ["Refinery"], 8),
    ("Alternate: Coated Iron Canister", [("Copper Sheet",1),("Iron Plate",2)], [("Empty Canister",4)], ["Assembler"], 4),
    ("Alternate: Coated Iron Plate", [("Iron Ingot",5),("Plastic",1)], [("Iron Plate",10)], ["Assembler"], 8),
    ("Alternate: Coke Steel Ingot", [("Iron Ore",15),("Petroleum Coke",15)], [("Steel Ingot",20)], ["Foundry"], 12),
    ("Alternate: Compacted Coal", [("Coal",5),("Sulfur",5)], [("Compacted Coal",5)], ["Assembler"], 12),
    ("Alternate: Compacted Steel Ingot", [("Compacted Coal",1),("Iron Ore",2)], [("Steel Ingot",4)], ["Foundry"], 24),
    ("Alternate: Cooling Device", [("Heat Sink",4),("Motor",1),("Nitrogen Gas",24)], [("Cooling System",2)], ["Blender"], 24),
    ("Alternate: Copper Alloy Ingot", [("Copper Ore",5),("Iron Ore",5)], [("Copper Ingot",10)], ["Foundry"], 6),
    ("Alternate: Copper Rotor", [("Copper Sheet",6),("Screw",52)], [("Rotor",3)], ["Assembler"], 16),
    ("Alternate: Crystal Computer", [("Circuit Board",3),("Crystal Oscillator",1)], [("Computer",2)], ["Assembler"], 36),
    ("Alternate: Dark Matter Crystallization", [("Dark Matter Residue",10)], [("Dark Matter Crystal",1)], ["Particle Accelerator"], 3),
    ("Alternate: Dark Matter Trap", [("Dark Matter Residue",5),("Time Crystal",1)], [("Dark Matter Crystal",2)], ["Particle Accelerator"], 2),
    ("Alternate: Dark-Ion Fuel", [("Dark Matter Crystal",4),("Packaged Rocket Fuel",12)], [("Compacted Coal",2),("Ionized Fuel",10)], ["Converter"], 3),
    ("Alternate: Diluted Fuel", [("Heavy Oil Residue",5),("Water",10)], [("Fuel",10)], ["Blender"], 6),
    ("Alternate: Diluted Packaged Fuel", [("Heavy Oil Residue",1),("Packaged Water",2)], [("Packaged Fuel",2)], ["Refinery"], 2),
    ("Alternate: Distilled Silica", [("Dissolved Silica",12),("Limestone",5),("Water",10)], [("Silica",27),("Water",8)], ["Blender"], 6),
    ("Alternate: Electric Motor", [("Electromagnetic Control Rod",1),("Rotor",2)], [("Motor",2)], ["Assembler"], 16),
    ("Alternate: Electrode Aluminum Scrap", [("Alumina Solution",12),("Petroleum Coke",4)], [("Aluminum Scrap",20),("Water",7)], ["Refinery"], 4),
    ("Alternate: Electrode Circuit Board", [("Petroleum Coke",8),("Rubber",4)], [("Circuit Board",1)], ["Assembler"], 12),
    ("Alternate: Electromagnetic Connection Rod", [("High-Speed Connector",1),("Stator",2)], [("Electromagnetic Control Rod",2)], ["Assembler"], 15),
    ("Alternate: Encased Industrial Pipe", [("Concrete",5),("Steel Pipe",6)], [("Encased Industrial Beam",1)], ["Assembler"], 15),
    ("Alternate: Fertile Uranium", [("Nitric Acid",3),("Uranium Waste",5),("Uranium",5),("Sulfuric Acid",5)], [("Non-Fissile Uranium",20),("Water",8)], ["Blender"], 12),
    ("Alternate: Fine Black Powder", [("Compacted Coal",2),("Sulfur",1)], [("Black Powder",6)], ["Assembler"], 8),
    ("Alternate: Fine Concrete", [("Silica",3),("Limestone",12)], [("Concrete",10)], ["Assembler"], 12),
    ("Alternate: Flexible Framework", [("Modular Frame",1),("Rubber",8),("Steel Beam",6)], [("Versatile Framework",2)], ["Manufacturer"], 16),
    ("Alternate: Fused Quartz Crystal", [("Coal",12),("Raw Quartz",25)], [("Quartz Crystal",18)], ["Foundry"], 20),
    ("Alternate: Fused Quickwire", [("Copper Ingot",5),("Caterium Ingot",1)], [("Quickwire",12)], ["Assembler"], 8),
    ("Alternate: Fused Wire", [("Copper Ingot",4),("Caterium Ingot",1)], [("Wire",30)], ["Assembler"], 20),
    ("Alternate: Heat Exchanger", [("Aluminum Casing",3),("Rubber",3)], [("Heat Sink",1)], ["Assembler"], 6),
    ("Alternate: Heat-Fused Frame", [("Aluminum Ingot",50),("Fuel",10),("Heavy Modular Frame",1),("Nitric Acid",8)], [("Fused Modular Frame",1)], ["Blender"], 20),
    ("Alternate: Heavy Encased Frame", [("Concrete",22),("Modular Frame",8),("Steel Pipe",36),("Encased Industrial Beam",10)], [("Heavy Modular Frame",3)], ["Manufacturer"], 64),
    ("Alternate: Heavy Flexible Frame", [("Screw",104),("Modular Frame",5),("Rubber",20),("Encased Industrial Beam",3)], [("Heavy Modular Frame",1)], ["Manufacturer"], 16),
    ("Alternate: Heavy Oil Residue", [("Crude Oil",3)], [("Heavy Oil Residue",4),("Polymer Resin",2)], ["Refinery"], 6),
    ("Alternate: Infused Uranium Cell", [("Quickwire",15),("Uranium",5),("Silica",3),("Sulfur",5)], [("Encased Uranium Cell",4)], ["Manufacturer"], 12),
    ("Alternate: Instant Plutonium Cell", [("Aluminum Casing",20),("Non-Fissile Uranium",150)], [("Encased Plutonium Cell",20)], ["Particle Accelerator"], 120),
    ("Alternate: Instant Scrap", [("Coal",10),("Bauxite",15),("Sulfuric Acid",5),("Water",6)], [("Aluminum Scrap",30),("Water",5)], ["Blender"], 6),
    ("Alternate: Insulated Cable", [("Rubber",6),("Wire",9)], [("Cable",20)], ["Assembler"], 12),
    ("Alternate: Insulated Crystal Oscillator", [("AI Limiter",1),("Quartz Crystal",10),("Rubber",7)], [("Crystal Oscillator",1)], ["Manufacturer"], 32),
    ("Alternate: Iron Alloy Ingot", [("Copper Ore",2),("Iron Ore",8)], [("Iron Ingot",15)], ["Foundry"], 12),
    ("Alternate: Iron Pipe", [("Iron Ingot",20)], [("Steel Pipe",5)], ["Constructor"], 12),
    ("Alternate: Iron Wire", [("Iron Ingot",5)], [("Wire",9)], ["Constructor"], 24),
    ("Alternate: Leached Caterium Ingot", [("Caterium Ore",9),("Sulfuric Acid",5)], [("Caterium Ingot",6)], ["Refinery"], 10),
    ("Alternate: Leached Copper Ingot", [("Copper Ore",9),("Sulfuric Acid",5)], [("Copper Ingot",22)], ["Refinery"], 12),
    ("Alternate: Leached Iron ingot", [("Iron Ore",5),("Sulfuric Acid",1)], [("Iron Ingot",10)], ["Refinery"], 6),
    ("Alternate: Molded Beam", [("Concrete",16),("Steel Ingot",24)], [("Steel Beam",9)], ["Foundry"], 12),
    ("Alternate: Molded Steel Pipe", [("Concrete",3),("Steel Ingot",5)], [("Steel Pipe",5)], ["Foundry"], 6),
    ("Alternate: Nitro Rocket Fuel", [("Coal",2),("Fuel",4),("Nitrogen Gas",3),("Sulfur",4)], [("Compacted Coal",1),("Rocket Fuel",6)], ["Blender"], 2.4),
    ("Alternate: OC Supercomputer", [("Cooling System",2),("Radio Control Unit",2)], [("Supercomputer",1)], ["Assembler"], 20),
    ("Alternate: Oil-Based Diamonds", [("Crude Oil",10)], [("Diamonds",2)], ["Particle Accelerator"], 3),
    ("Alternate: Petroleum Diamonds", [("Petroleum Coke",24)], [("Diamonds",1)], ["Particle Accelerator"], 2),
    ("Alternate: Pink Diamonds", [("Coal",8),("Quartz Crystal",3)], [("Diamonds",1)], ["Converter"], 4),
    ("Alternate: Plastic AI Limiter", [("Quickwire",30),("Plastic",7)], [("AI Limiter",2)], ["Assembler"], 15),
    ("Alternate: Plastic Smart Plating", [("Reinforced Iron Plate",1),("Plastic",3),("Rotor",1)], [("Smart Plating",2)], ["Manufacturer"], 24),
    ("Alternate: Plutonium Fuel Unit", [("Encased Plutonium Cell",20),("Pressure Conversion Cube",1)], [("Plutonium Fuel Rod",1)], ["Assembler"], 120),
    ("Alternate: Polyester Fabric", [("Polymer Resin",1),("Water",1)], [("Fabric",1)], ["Refinery"], 2),
    ("Alternate: Polymer Resin", [("Crude Oil",6)], [("Heavy Oil Residue",2),("Polymer Resin",13)], ["Refinery"], 6),
    ("Alternate: Pure Aluminum Ingot", [("Aluminum Scrap",2)], [("Aluminum Ingot",1)], ["Smelter"], 2),
    ("Alternate: Pure Caterium Ingot", [("Caterium Ore",2),("Water",2)], [("Caterium Ingot",1)], ["Refinery"], 5),
    ("Alternate: Pure Copper Ingot", [("Copper Ore",6),("Water",4)], [("Copper Ingot",15)], ["Refinery"], 24),
    ("Alternate: Pure Iron Ingot", [("Iron Ore",7),("Water",4)], [("Iron Ingot",13)], ["Refinery"], 12),
    ("Alternate: Pure Quartz Crystal", [("Raw Quartz",9),("Water",5)], [("Quartz Crystal",7)], ["Refinery"], 8),
    ("Alternate: Quartz Purification", [("Nitric Acid",2),("Raw Quartz",24)], [("Dissolved Silica",12),("Quartz Crystal",15)], ["Refinery"], 12),
    ("Alternate: Quickwire Cable", [("Quickwire",3),("Rubber",2)], [("Cable",11)], ["Assembler"], 24),
    ("Alternate: Quickwire Stator", [("Quickwire",15),("Steel Pipe",4)], [("Stator",2)], ["Assembler"], 15),
    ("Alternate: Radio Connection Unit", [("Heat Sink",4),("High-Speed Connector",2),("Quartz Crystal",12)], [("Radio Control Unit",1)], ["Manufacturer"], 16),
    ("Alternate: Radio Control System", [("Aluminum Casing",60),("Circuit Board",10),("Crystal Oscillator",1),("Rubber",30)], [("Radio Control Unit",3)], ["Manufacturer"], 40),
    ("Alternate: Recycled Plastic", [("Fuel",6),("Rubber",6)], [("Plastic",12)], ["Refinery"], 12),
    ("Alternate: Recycled Rubber", [("Fuel",6),("Plastic",6)], [("Rubber",12)], ["Refinery"], 12),
    ("Alternate: Rigor Motor", [("Crystal Oscillator",1),("Rotor",3),("Stator",3)], [("Motor",6)], ["Manufacturer"], 48),
    ("Alternate: Rubber Concrete", [("Rubber",2),("Limestone",10)], [("Concrete",9)], ["Assembler"], 6),
    ("Alternate: Silicon Circuit Board", [("Copper Sheet",11),("Silica",11)], [("Circuit Board",5)], ["Assembler"], 24),
    ("Alternate: Silicon High-Speed Connector", [("Circuit Board",2),("Quickwire",60),("Silica",25)], [("High-Speed Connector",2)], ["Manufacturer"], 40),
    ("Alternate: Sloppy Alumina", [("Bauxite",10),("Water",10)], [("Alumina Solution",12)], ["Refinery"], 3),
    ("Alternate: Solid Steel Ingot", [("Coal",2),("Iron Ingot",2)], [("Steel Ingot",3)], ["Foundry"], 3),
    ("Alternate: Steamed Copper Sheet", [("Copper Ingot",3),("Water",3)], [("Copper Sheet",3)], ["Refinery"], 8),
    ("Alternate: Steel Canister", [("Steel Ingot",4)], [("Empty Canister",4)], ["Constructor"], 6),
    ("Alternate: Steel Cast Plate", [("Iron Ingot",1),("Steel Ingot",1)], [("Iron Plate",3)], ["Foundry"], 4),
    ("Alternate: Steel Rod", [("Steel Ingot",1)], [("Iron Rod",4)], ["Constructor"], 5),
    ("Alternate: Steel Rotor", [("Steel Pipe",2),("Wire",6)], [("Rotor",1)], ["Assembler"], 12),
    ("Alternate: Steel Screw", [("Steel Beam",1)], [("Screw",52)], ["Constructor"], 12),
    ("Alternate: Steeled Frame", [("Reinforced Iron Plate",2),("Steel Pipe",10)], [("Modular Frame",3)], ["Assembler"], 60),
    ("Alternate: Stitched Iron Plate", [("Iron Plate",10),("Wire",20)], [("Reinforced Iron Plate",3)], ["Assembler"], 32),
    ("Alternate: Super-State Computer", [("Battery",10),("Computer",3),("Electromagnetic Control Rod",1),("Wire",25)], [("Supercomputer",1)], ["Manufacturer"], 25),
    ("Alternate: Tempered Caterium Ingot", [("Caterium Ore",6),("Petroleum Coke",2)], [("Caterium Ingot",3)], ["Foundry"], 8),
    ("Alternate: Tempered Copper Ingot", [("Copper Ore",5),("Petroleum Coke",8)], [("Copper Ingot",12)], ["Foundry"], 12),
    ("Alternate: Turbo Blend Fuel", [("Heavy Oil Residue",4),("Fuel",2),("Petroleum Coke",3),("Sulfur",3)], [("Turbofuel",6)], ["Blender"], 8),
    ("Alternate: Turbo Diamonds", [("Coal",30),("Packaged Turbofuel",2)], [("Diamonds",3)], ["Particle Accelerator"], 3),
    ("Alternate: Turbo Electric Motor", [("Electromagnetic Control Rod",5),("Radio Control Unit",9),("Motor",7),("Rotor",7)], [("Turbo Motor",3)], ["Manufacturer"], 64),
    ("Alternate: Turbo Heavy Fuel", [("Compacted Coal",4),("Heavy Oil Residue",5)], [("Turbofuel",4)], ["Refinery"], 8),
    ("Alternate: Turbo Pressure Motor", [("Motor",4),("Packaged Nitrogen Gas",24),("Pressure Conversion Cube",1),("Stator",8)], [("Turbo Motor",2)], ["Manufacturer"], 32),
    ("Alternate: Uranium Fuel Unit", [("Crystal Oscillator",3),("Electromagnetic Control Rod",10),("Rotor",10),("Encased Uranium Cell",100)], [("Uranium Fuel Rod",3)], ["Manufacturer"], 300),
    ("Alternate: Wet Concrete", [("Limestone",6),("Water",5)], [("Concrete",4)], ["Refinery"], 3),
    ("Alumina Solution", [("Bauxite",12),("Water",18)], [("Alumina Solution",12),("Silica",5)], ["Refinery"], 6),
    ("Aluminum Casing", [("Aluminum Ingot",3)], [("Aluminum Casing",2)], ["Constructor"], 2),
    ("Aluminum Ingot", [("Aluminum Scrap",6),("Silica",5)], [("Aluminum Ingot",4)], ["Foundry"], 4),
    ("Aluminum Scrap", [("Alumina Solution",4),("Coal",2)], [("Aluminum Scrap",6),("Water",2)], ["Refinery"], 1),
    ("Assembly Director System", [("Supercomputer",1),("Adaptive Control Unit",2)], [("Assembly Director System",1)], ["Assembler"], 80),
    ("Automated Wiring", [("Cable",20),("Stator",1)], [("Automated Wiring",1)], ["Assembler"], 24),
    ("Ballistic Warp Drive", [("Dark Matter Crystal",40),("Superposition Oscillator",2),("Singularity Cell",5),("Thermal Propulsion Rocket",1)], [("Ballistic Warp Drive",1)], ["Manufacturer"], 60),
    ("Battery", [("Alumina Solution",2),("Aluminum Casing",1),("Sulfuric Acid",2.5)], [("Battery",1),("Water",1.5)], ["Blender"], 3),
    ("Bauxite (Caterium)", [("Caterium Ore",15),("Reanimated SAM",1)], [("Bauxite",12)], ["Converter"], 6),
    ("Bauxite (Copper)", [("Copper Ore",18),("Reanimated SAM",1)], [("Bauxite",12)], ["Converter"], 6),
    ("Biochemical Sculptor", [("Ficsite Trigon",80),("Assembly Director System",1),("Water",20)], [("Biochemical Sculptor",4)], ["Blender"], 120),
    ("Biomass (Leaves)", [("Leaves",10)], [("Biomass",5)], ["Constructor"], 5),
    ("Biomass (Mycelia)", [("Mycelia",1)], [("Biomass",10)], ["Constructor"], 4),
    ("Biomass (Wood)", [("Wood",4)], [("Biomass",20)], ["Constructor"], 4),
    ("Black Powder", [("Coal",1),("Sulfur",1)], [("Black Powder",2)], ["Assembler"], 4),
    ("Cable", [("Wire",2)], [("Cable",1)], ["Constructor"], 2),
    ("Caterium Ingot", [("Caterium Ore",3)], [("Caterium Ingot",1)], ["Smelter"], 4),
    ("Caterium Ore (Copper)", [("Copper Ore",15),("Reanimated SAM",1)], [("Caterium Ore",12)], ["Converter"], 6),
    ("Caterium Ore (Quartz)", [("Raw Quartz",12),("Reanimated SAM",1)], [("Caterium Ore",12)], ["Converter"], 6),
    ("Circuit Board", [("Copper Sheet",2),("Plastic",4)], [("Circuit Board",1)], ["Assembler"], 8),
    ("Coal (Iron)", [("Iron Ore",18),("Reanimated SAM",1)], [("Coal",12)], ["Converter"], 6),
    ("Coal (Limestone)", [("Reanimated SAM",1),("Limestone",36)], [("Coal",12)], ["Converter"], 6),
    ("Computer", [("Cable",8),("Circuit Board",4),("Plastic",16)], [("Computer",1)], ["Manufacturer"], 24),
    ("Concrete", [("Limestone",3)], [("Concrete",1)], ["Constructor"], 4),
    ("Cooling System", [("Heat Sink",2),("Nitrogen Gas",25),("Rubber",2),("Water",5)], [("Cooling System",1)], ["Blender"], 10),
    ("Copper Ingot", [("Copper Ore",1)], [("Copper Ingot",1)], ["Smelter"], 2),
    ("Copper Ore (Quartz)", [("Raw Quartz",10),("Reanimated SAM",1)], [("Copper Ore",12)], ["Converter"], 6),
    ("Copper Ore (Sulfur)", [("Reanimated SAM",1),("Sulfur",12)], [("Copper Ore",12)], ["Converter"], 6),
    ("Copper Powder", [("Copper Ingot",30)], [("Copper Powder",5)], ["Constructor"], 6),
    ("Copper Sheet", [("Copper Ingot",2)], [("Copper Sheet",1)], ["Constructor"], 6),
    ("Crystal Oscillator", [("Cable",28),("Reinforced Iron Plate",5),("Quartz Crystal",36)], [("Crystal Oscillator",2)], ["Manufacturer"], 120),
    ("Dark Matter Crystal", [("Dark Matter Residue",5),("Diamonds",1)], [("Dark Matter Crystal",1)], ["Particle Accelerator"], 2),
    ("Dark Matter Residue", [("Reanimated SAM",5)], [("Dark Matter Residue",10)], ["Converter"], 6),
    ("Diamonds", [("Coal",20)], [("Diamonds",1)], ["Particle Accelerator"], 2),
    ("Electromagnetic Control Rod", [("AI Limiter",2),("Stator",3)], [("Electromagnetic Control Rod",2)], ["Assembler"], 30),
    ("Empty Canister", [("Plastic",2)], [("Empty Canister",4)], ["Constructor"], 4),
    ("Empty Fluid Tank", [("Aluminum Ingot",1)], [("Empty Fluid Tank",1)], ["Constructor"], 1),
    ("Encased Industrial Beam", [("Concrete",6),("Steel Beam",3)], [("Encased Industrial Beam",1)], ["Assembler"], 10),
    ("Encased Plutonium Cell", [("Concrete",4),("Plutonium Pellet",2)], [("Encased Plutonium Cell",1)], ["Assembler"], 12),
    ("Encased Uranium Cell", [("Concrete",3),("Uranium",10),("Sulfuric Acid",8)], [("Sulfuric Acid",2),("Encased Uranium Cell",5)], ["Blender"], 12),
    ("Excited Photonic Matter", [], [("Excited Photonic Matter",10)], ["Converter"], 3),
    ("Fabric", [("Biomass",5),("Mycelia",1)], [("Fabric",1)], ["Assembler"], 4),
    ("Ficsite Ingot (Aluminum)", [("Aluminum Ingot",4),("Reanimated SAM",2)], [("Ficsite Ingot",1)], ["Converter"], 2),
    ("Ficsite Ingot (Caterium)", [("Caterium Ingot",4),("Reanimated SAM",3)], [("Ficsite Ingot",1)], ["Converter"], 4),
    ("Ficsite Ingot (Iron)", [("Iron Ingot",24),("Reanimated SAM",4)], [("Ficsite Ingot",1)], ["Converter"], 6),
    ("Ficsite Trigon", [("Ficsite Ingot",1)], [("Ficsite Trigon",3)], ["Constructor"], 6),
    ("Ficsonium", [("Dark Matter Residue",20),("Plutonium Waste",1),("Singularity Cell",1)], [("Ficsonium",1)], ["Particle Accelerator"], 6),
    ("Ficsonium Fuel Rod", [("Electromagnetic Control Rod",2),("Ficsite Trigon",40),("Ficsonium",2),("Excited Photonic Matter",20)], [("Dark Matter Residue",20),("Ficsonium Fuel Rod",1)], ["Quantum Encoder"], 24),
    ("Fuel", [("Crude Oil",6)], [("Fuel",4),("Polymer Resin",3)], ["Refinery"], 6),
    ("Fused Modular Frame", [("Aluminum Casing",50),("Heavy Modular Frame",1),("Nitrogen Gas",25)], [("Fused Modular Frame",1)], ["Blender"], 40),
    ("Heat Sink", [("Alclad Aluminum Sheet",5),("Copper Sheet",3)], [("Heat Sink",1)], ["Assembler"], 8),
    ("Heavy Modular Frame", [("Screw",120),("Modular Frame",5),("Steel Pipe",20),("Encased Industrial Beam",5)], [("Heavy Modular Frame",1)], ["Manufacturer"], 30),
    ("High-Speed Connector", [("Cable",10),("Circuit Board",1),("Quickwire",56)], [("High-Speed Connector",1)], ["Manufacturer"], 16),
    ("Ionized Fuel", [("Power Shard",1),("Rocket Fuel",16)], [("Compacted Coal",2),("Ionized Fuel",16)], ["Refinery"], 24),
    ("Iron Ingot", [("Iron Ore",1)], [("Iron Ingot",1)], ["Smelter"], 2),
    ("Iron Ore (Limestone)", [("Reanimated SAM",1),("Limestone",24)], [("Iron Ore",12)], ["Converter"], 6),
    ("Iron Plate", [("Iron Ingot",3)], [("Iron Plate",2)], ["Constructor"], 6),
    ("Iron Rebar", [("Iron Rod",1)], [("Iron Rebar",1)], ["Constructor"], 4),
    ("Iron Rod", [("Iron Ingot",1)], [("Iron Rod",1)], ["Constructor"], 4),
    ("Limestone (Sulfur)", [("Reanimated SAM",1),("Sulfur",2)], [("Limestone",12)], ["Converter"], 6),
    ("Liquid Biofuel", [("Solid Biofuel",6),("Water",3)], [("Liquid Biofuel",4)], ["Refinery"], 4),
    ("Magnetic Field Generator", [("Electromagnetic Control Rod",2),("Versatile Framework",5)], [("Magnetic Field Generator",2)], ["Assembler"], 120),
    ("Modular Engine", [("Motor",2),("Rubber",15),("Smart Plating",2)], [("Modular Engine",1)], ["Manufacturer"], 60),
    ("Modular Frame", [("Reinforced Iron Plate",3),("Iron Rod",12)], [("Modular Frame",2)], ["Assembler"], 60),
    ("Motor", [("Rotor",2),("Stator",2)], [("Motor",1)], ["Assembler"], 12),
    ("Neural-Quantum Processor", [("Supercomputer",1),("Ficsite Trigon",15),("Excited Photonic Matter",25),("Time Crystal",5)], [("Dark Matter Residue",25),("Neural-Quantum Processor",1)], ["Quantum Encoder"], 20),
    ("Nitric Acid", [("Iron Plate",1),("Nitrogen Gas",12),("Water",3)], [("Nitric Acid",3)], ["Blender"], 6),
    ("Nitrogen Gas (Bauxite)", [("Bauxite",10),("Reanimated SAM",1)], [("Nitrogen Gas",12)], ["Converter"], 6),
    ("Nitrogen Gas (Caterium)", [("Caterium Ore",12),("Reanimated SAM",1)], [("Nitrogen Gas",12)], ["Converter"], 6),
    ("Nobelisk", [("Black Powder",2),("Steel Pipe",2)], [("Nobelisk",1)], ["Assembler"], 6),
    ("Non-Fissile Uranium", [("Nitric Acid",6),("Uranium Waste",15),("Silica",10),("Sulfuric Acid",6)], [("Non-Fissile Uranium",20),("Water",6)], ["Blender"], 24),
    ("Nuclear Pasta", [("Copper Powder",200),("Pressure Conversion Cube",1)], [("Nuclear Pasta",1)], ["Particle Accelerator"], 120),
    ("Packaged Alumina Solution", [("Alumina Solution",2),("Empty Canister",2)], [("Packaged Alumina Solution",2)], ["Packager"], 1),
    ("Packaged Fuel", [("Empty Canister",2),("Fuel",2)], [("Packaged Fuel",2)], ["Packager"], 3),
    ("Packaged Heavy Oil Residue", [("Empty Canister",2),("Heavy Oil Residue",2)], [("Packaged Heavy Oil Residue",2)], ["Packager"], 4),
    ("Packaged Ionized Fuel", [("Empty Fluid Tank",2),("Ionized Fuel",4)], [("Packaged Ionized Fuel",2)], ["Packager"], 3),
    ("Packaged Liquid Biofuel", [("Empty Canister",2),("Liquid Biofuel",2)], [("Packaged Liquid Biofuel",2)], ["Packager"], 3),
    ("Packaged Nitric Acid", [("Empty Fluid Tank",1),("Nitric Acid",1)], [("Packaged Nitric Acid",1)], ["Packager"], 2),
    ("Packaged Nitrogen Gas", [("Empty Fluid Tank",1),("Nitrogen Gas",4)], [("Packaged Nitrogen Gas",1)], ["Packager"], 1),
    ("Packaged Oil", [("Empty Canister",2),("Crude Oil",2)], [("Packaged Oil",2)], ["Packager"], 4),
    ("Packaged Rocket Fuel", [("Empty Fluid Tank",1),("Rocket Fuel",2)], [("Packaged Rocket Fuel",1)], ["Packager"], 1),
    ("Packaged Sulfuric Acid", [("Empty Canister",2),("Sulfuric Acid",2)], [("Packaged Sulfuric Acid",2)], ["Packager"], 3),
    ("Packaged Turbofuel", [("Empty Canister",2),("Turbofuel",2)], [("Packaged Turbofuel",2)], ["Packager"], 6),
    ("Packaged Water", [("Empty Canister",2),("Water",2)], [("Packaged Water",2)], ["Packager"], 2),
    ("Petroleum Coke", [("Heavy Oil Residue",4)], [("Petroleum Coke",12)], ["Refinery"], 6),
    ("Plastic", [("Crude Oil",3)], [("Heavy Oil Residue",1),("Plastic",2)], ["Refinery"], 6),
    ("Plutonium Fuel Rod", [("Heat Sink",10),("Electromagnetic Control Rod",6),("Encased Plutonium Cell",30),("Steel Beam",18)], [("Plutonium Fuel Rod",1)], ["Manufacturer"], 240),
    ("Plutonium Pellet", [("Non-Fissile Uranium",100),("Uranium Waste",25)], [("Plutonium Pellet",30)], ["Particle Accelerator"], 60),
    ("Pressure Conversion Cube", [("Fused Modular Frame",1),("Radio Control Unit",2)], [("Pressure Conversion Cube",1)], ["Assembler"], 60),
    ("Quartz Crystal", [("Raw Quartz",5)], [("Quartz Crystal",3)], ["Constructor"], 8),
    ("Quickwire", [("Caterium Ingot",1)], [("Quickwire",5)], ["Constructor"], 5),
    ("Radio Control Unit", [("Aluminum Casing",32),("Computer",2),("Crystal Oscillator",1)], [("Radio Control Unit",2)], ["Manufacturer"], 48),
    ("Raw Quartz (Bauxite)", [("Bauxite",10),("Reanimated SAM",1)], [("Raw Quartz",12)], ["Converter"], 6),
    ("Raw Quartz (Coal)", [("Coal",24),("Reanimated SAM",1)], [("Raw Quartz",12)], ["Converter"], 6),
    ("Reanimated SAM", [("SAM",4)], [("Reanimated SAM",1)], ["Constructor"], 2),
    ("Reinforced Iron Plate", [("Iron Plate",6),("Screw",12)], [("Reinforced Iron Plate",1)], ["Assembler"], 12),
    ("Residual Fuel", [("Heavy Oil Residue",6)], [("Fuel",4)], ["Refinery"], 6),
    ("Residual Plastic", [("Polymer Resin",6),("Water",2)], [("Plastic",2)], ["Refinery"], 6),
    ("Residual Rubber", [("Polymer Resin",4),("Water",4)], [("Rubber",2)], ["Refinery"], 6),
    ("Rocket Fuel", [("Turbofuel",6),("Nitric Acid",1)], [("Compacted Coal",1),("Rocket Fuel",10)], ["Blender"], 6),
    ("Rotor", [("Iron Rod",5),("Screw",25)], [("Rotor",1)], ["Assembler"], 15),
    ("Rubber", [("Crude Oil",3)], [("Heavy Oil Residue",2),("Rubber",2)], ["Refinery"], 6),
    ("SAM Fluctuator", [("Reanimated SAM",6),("Steel Pipe",3),("Wire",5)], [("SAM Fluctuator",1)], ["Manufacturer"], 6),
    ("Screw", [("Iron Rod",1)], [("Screw",4)], ["Constructor"], 6),
    ("Silica", [("Raw Quartz",3)], [("Silica",5)], ["Constructor"], 8),
    ("Singularity Cell", [("Concrete",200),("Dark Matter Crystal",20),("Iron Plate",100),("Nuclear Pasta",1)], [("Singularity Cell",10)], ["Manufacturer"], 60),
    ("Smart Plating", [("Reinforced Iron Plate",1),("Rotor",1)], [("Smart Plating",1)], ["Assembler"], 30),
    ("Smokeless Powder", [("Black Powder",2),("Heavy Oil Residue",1)], [("Smokeless Powder",2)], ["Refinery"], 6),
    ("Solid Biofuel", [("Biomass",8)], [("Solid Biofuel",4)], ["Constructor"], 4),
    ("Stator", [("Steel Pipe",3),("Wire",8)], [("Stator",1)], ["Assembler"], 12),
    ("Steel Beam", [("Steel Ingot",4)], [("Steel Beam",1)], ["Constructor"], 4),
    ("Steel Ingot", [("Coal",3),("Iron Ore",3)], [("Steel Ingot",3)], ["Foundry"], 4),
    ("Steel Pipe", [("Steel Ingot",3)], [("Steel Pipe",2)], ["Constructor"], 6),
    ("Sulfur (Coal)", [("Coal",20),("Reanimated SAM",1)], [("Sulfur",12)], ["Converter"], 6),
    ("Sulfur (Iron)", [("Iron Ore",30),("Reanimated SAM",1)], [("Sulfur",12)], ["Converter"], 6),
    ("Sulfuric Acid", [("Sulfur",5),("Water",5)], [("Sulfuric Acid",5)], ["Refinery"], 6),
    ("Supercomputer", [("AI Limiter",2),("Computer",4),("High-Speed Connector",3),("Plastic",28)], [("Supercomputer",1)], ["Manufacturer"], 32),
    ("Superposition Oscillator", [("Alclad Aluminum Sheet",9),("Crystal Oscillator",1),("Dark Matter Crystal",6),("Excited Photonic Matter",25)], [("Dark Matter Residue",25),("Superposition Oscillator",1)], ["Quantum Encoder"], 12),
    ("Synthetic Power Shard", [("Dark Matter Crystal",2),("Excited Photonic Matter",12),("Quartz Crystal",12),("Time Crystal",2)], [("Power Shard",1),("Dark Matter Residue",12)], ["Quantum Encoder"], 12),
    ("Thermal Propulsion Rocket", [("Cooling System",6),("Fused Modular Frame",2),("Turbo Motor",2),("Modular Engine",5)], [("Thermal Propulsion Rocket",2)], ["Manufacturer"], 120),
    ("Time Crystal", [("Diamonds",2)], [("Time Crystal",1)], ["Converter"], 10),
    ("Turbo Motor", [("Cooling System",4),("Radio Control Unit",2),("Motor",4),("Rubber",24)], [("Turbo Motor",1)], ["Manufacturer"], 32),
    ("Turbofuel", [("Compacted Coal",4),("Fuel",6)], [("Turbofuel",5)], ["Refinery"], 16),
    ("Uranium Fuel Rod", [("Electromagnetic Control Rod",5),("Encased Industrial Beam",3),("Encased Uranium Cell",50)], [("Uranium Fuel Rod",1)], ["Manufacturer"], 150),
    ("Uranium Ore (Bauxite)", [("Bauxite",48),("Reanimated SAM",1)], [("Uranium",12)], ["Converter"], 6),
    ("Versatile Framework", [("Modular Frame",1),("Steel Beam",12)], [("Versatile Framework",2)], ["Assembler"], 24),
    ("Wire", [("Copper Ingot",1)], [("Wire",2)], ["Constructor"], 4),
]

# Raw resource items (extractable, not crafted)
RAW_RESOURCES = {"Iron Ore","Copper Ore","Limestone","Coal","Caterium Ore","Raw Quartz","Sulfur",
                 "Bauxite","Uranium","SAM","Crude Oil","Water","Nitrogen Gas",
                 "Leaves","Wood","Mycelia","Alien Protein",
                 "Blue Power Slug","Yellow Power Slug","Purple Power Slug","Power Shard"}

print(f"Recipes loaded: {len(RECIPES)}")
